name: karyawan_mobile
description: Karyawan Mobile App - Monitoring Maintenance
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared:
    path: ../../packages/shared
  flutter_riverpod: ^2.6.1
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  cached_network_image: ^3.4.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  image_path: "../../assets/icon/NKP.png"

flutter:
  uses-material-design: true
  assets:
    - ../../assets/icon/NKP.webp
